
// File Encoding: UTF-8

#pragma once

#ifndef _INC_COM_RMDUST_COLOR
#define _INC_COM_RMDUST_COLOR

#define COLOR_BLACK 48
#define COLOR_BLUE 49
#define COLOR_GREEN 50
#define COLOR_AQUA 51
#define COLOR_RED 52
#define COLOR_PURPLE 53
#define COLOR_YELLO 54
#define COLOR_WHITE 55
#define COLOR_GRAY 56
#define COLOR_LIGHTBLUE 57
#define COLOR_LIGHTGREEN 65
#define COLOR_LIGHTAQUA 66
#define COLOR_LIGHTRED 67
#define COLOR_LIGHTPURPLE 68
#define COLOR_LIGHTYELLOW 69
#define COLOR_BRIGHTWHITE 70

#define HEX_COLOR_BLACK 0
#define HEX_COLOR_BLUE 1
#define HEX_COLOR_GREEN 2
#define HEX_COLOR_AQUA 3
#define HEX_COLOR_RED 4
#define HEX_COLOR_PURPLE 5
#define HEX_COLOR_YELLO 6
#define HEX_COLOR_WHITE 7
#define HEX_COLOR_GRAY 8
#define HEX_COLOR_LIGHTBLUE 9
#define HEX_COLOR_LIGHTGREEN A
#define HEX_COLOR_LIGHTAQUA B
#define HEX_COLOR_LIGHTRED C
#define HEX_COLOR_LIGHTPURPLE D
#define HEX_COLOR_LIGHTYELLOW E
#define HEX_COLOR_BRIGHTWHITE F

#endif